import "bootstrap/dist/css/bootstrap.css";
import "../styles/globals.css";

export const metadata = {
  title: "React App",
  description: "Generated by create next app",
};

export default function RootLayout({ Component, pageProps }) {
  return (
    <Component {...pageProps} />
  );
}
