'use client';

import React from 'react';
import App from "../src/App";

export const metadata = {
  title: "React App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div>
      <App />
    </div>
  );
}
