import 'bootstrap/dist/css/bootstrap.css';
import '/styles/styles.css';

export const metadata = {
  title: "What is React",
  description: "Generated by Peter Kellner for What is React Course",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
